admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Default:login }

admin_login_check:
    path: /login_check

admin_logout:
    path: /logout

admin_usuarios:
    path:     /administrar
    defaults: { _controller: AdminBundle:Default:administrar }

admin_registro:
    path:     /registro
    defaults: { _controller: AdminBundle:Default:registro }

admin_usuarios_borrar:
    path:     /borrar/{id}
    defaults: { _controller: AdminBundle:Default:borrar}

